const ACTION_TYPE = {
  LOAD_CHART_RANKING: "LOAD_CHART_RANKING",
  LOAD_HOT_ALBUM: "LOAD_HOT_ALBUM",
  LOAD_HOT_ARTISTS: "LOAD_HOT_ARTISTS",
  LOAD_HOT_VIDEO: "LOAD_HOT_VIDEO",
  LOAD_NEWS: "LOAD_NEWS",
  LOAD_NEW_SONGS: "LOAD_NEW_SONGS",
  LOAD_PARTNERS: "LOAD_PARTNERS",
  LOAD_TODAY_SELECTION: "LOAD_TODAY_SELECTION",
  LOAD_RANKING_ALBUM: "LOAD_RANKING_ALBUM",
  LOAD_RANKING_MV: "LOAD_RANKING_MV",
  LOAD_RANKING_SONG: "LOAD_RANKING_SONG",
};
export default ACTION_TYPE;
